# Generated by Django 5.2.8 on 2025-11-30 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReelJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_script", models.TextField()),
                ("final_script", models.TextField(blank=True, null=True)),
                ("tone", models.CharField(default="neutral", max_length=50)),
                ("image", models.ImageField(upload_to="reels/images/")),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="reels/audio/"),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="reels/video/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("done", "done"),
                            ("error", "error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
