# Generated by Django 5.2.8 on 2025-11-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reeljob",
            name="script_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reeljob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("script_pending_approval", "script_pending_approval"),
                    ("script_approved", "script_approved"),
                    ("processing", "processing"),
                    ("done", "done"),
                    ("error", "error"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
