"""
SadTalker integration service.
"""
import subprocess
import pathlib
from django.conf import settings
from ..models import ReelJob


class SadTalkerError(Exception):
    """Custom exception for SadTalker errors."""
    pass


def run_sadtalker_for_reel(reel_job: ReelJob) -> str:
    """
    Use SadTalker to generate a talking-head video for reel_job.image + reel_job.audio_file.
    Save the resulting video under MEDIA_ROOT/reels/{job_id}/ and update reel_job.video_file.
    
    Args:
        reel_job: The ReelJob instance with image and audio_file set
    
    Returns:
        Absolute path to the generated video file
    
    Raises:
        SadTalkerError: If SadTalker execution fails
    """
    if not reel_job.image:
        raise SadTalkerError("ReelJob must have an image")
    
    if not reel_job.audio_file:
        raise SadTalkerError("ReelJob must have an audio_file")
    
    sadtalker_root = pathlib.Path(settings.SADTALKER_ROOT)
    if not sadtalker_root.exists():
        raise SadTalkerError(f"SadTalker root directory not found: {sadtalker_root}")
    
    # Get absolute paths
    image_path = pathlib.Path(reel_job.image.path).absolute()
    audio_path = pathlib.Path(reel_job.audio_file.path).absolute()
    
    if not image_path.exists():
        raise SadTalkerError(f"Image file not found: {image_path}")
    
    if not audio_path.exists():
        raise SadTalkerError(f"Audio file not found: {audio_path}")
    
    # Create job output directory
    job_output_dir = settings.MEDIA_ROOT / 'reels' / str(reel_job.id)
    job_output_dir.mkdir(parents=True, exist_ok=True)
    
    # Build the SadTalker command
    inference_script = sadtalker_root / 'inference.py'
    if not inference_script.exists():
        raise SadTalkerError(f"SadTalker inference.py not found: {inference_script}")
    
    cmd = [
        'python',
        str(inference_script),
        '--driven_audio', str(audio_path),
        '--source_image', str(image_path),
        '--result_dir', str(job_output_dir),
        '--enhancer', 'gfpgan',
        '--preprocess', 'full',
    ]
    
    try:
        # Run SadTalker
        result = subprocess.run(
            cmd,
            cwd=str(sadtalker_root),
            capture_output=True,
            text=True,
            check=True,
            timeout=600  # 10 minute timeout
        )
        
        # Search for the generated video file
        video_files = list(job_output_dir.rglob('*.mp4'))
        
        if not video_files:
            raise SadTalkerError("No video file generated by SadTalker")
        
        # Get the most recently modified video file
        video_file = max(video_files, key=lambda p: p.stat().st_mtime)
        
        # Copy/move to a standard location
        final_video_path = job_output_dir / 'video.mp4'
        if video_file != final_video_path:
            import shutil
            shutil.copy2(video_file, final_video_path)
        
        # Update the ReelJob model
        relative_video_path = f'reels/{reel_job.id}/video.mp4'
        reel_job.video_file.name = relative_video_path
        reel_job.save()
        
        return str(final_video_path.absolute())
    
    except subprocess.TimeoutExpired:
        reel_job.status = 'error'
        reel_job.error_message = "SadTalker execution timed out"
        reel_job.save()
        raise SadTalkerError("SadTalker execution timed out")
    
    except subprocess.CalledProcessError as e:
        error_msg = f"SadTalker failed: {e.stderr or e.stdout or str(e)}"
        reel_job.status = 'error'
        reel_job.error_message = error_msg
        reel_job.save()
        raise SadTalkerError(error_msg) from e
    
    except Exception as e:
        error_msg = f"Unexpected error running SadTalker: {str(e)}"
        reel_job.status = 'error'
        reel_job.error_message = error_msg
        reel_job.save()
        raise SadTalkerError(error_msg) from e

